stages:
    - deploy test
    - genera-sito

deploy-test test:
    stage: deploy test
    script:
        - echo "lanciata sincronizzazione..."
        - rsync -av --exclude 'storage' --exclude 'bootstrap/cache' --exclude '.git*' ./ /opt/neoassunti2024-cms/
        - echo "finita sincronizzazione"
        - echo "pulizia cache"
        - composer install --no-interaction --prefer-dist --optimize-autoloader
        - cd /opt/neoassunti2024-cms
        # - php artisan migrate:refresh --force
        # - php artisan migrate --force
        # - php artisan db:seed --force
        # - php artisan db:seed --class=StandardsTableSeeder
        # - php artisan db:seed --class=UsersTableSeeder
        - php artisan config:clear
        - php artisan cache:clear
        - php artisan event:clear

    tags:
        - neoassunti2024-cms-sviluppo
    only:
        - sviluppo

genera-sito:
    stage: genera-sito
    script:
        - cd /opt/neoassunti2024-cms
        - php please ssg:generate --workers=4
        - cd storage/app/static
        - rm -Rf .git
        - git init -b sviluppo
        - git config --global --add safe.directory /opt/neoassunti2024-cms/storage/app/static
        - git remote add origin https://upload_user:glpat-ZKAJ_fJu2or3V5Hmr2vF@gitlab.lombroso.indire.it/neoassunti/neoassunti2024/neoassunti-public.git
        - git fetch
        - git add . 
        - git pull origin sviluppo --no-rebase
        - git commit -m "update sito $CI_COMMIT_TIMESTAMP"
        - git push -u origin sviluppo
        - cd /opt/neoassunti2024-cms
        - rm -Rf storage/app/static
        - sudo chown -R apache:apache storage

    tags:
        - neoassunti2024-cms-sviluppo
    only:
        - sviluppo
    when: manual
